 site_name: Macpine
 site_url: https://beringresearch.github.com/alpine
 
 nav:
  - Home: index.md
  - Docs:
    - Installation: install.md
    - Quickstart: quickstart.md
    - Manage Instance:
      - Create an Instance: create_instance.md
      - Modify an instance: modify_instance.md
      - Create an LXD cintainer in Macpine: lxd_macpine.md
    
 #theme: material

 theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


 repo_url: https://github.com/beringresearch/macpine