name: Go report card

on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  workflow_dispatch:

jobs:
  refresh-scorecard:
    runs-on: ubuntu-latest
    steps:
    - uses: creekorful/goreportcard-action@v1.0
